-- Minimal Reference Schema for Oracle Fast E2E Tests
-- Simplified schema covering all comparison dimensions

-- Base table (standalone, no dependencies)
CREATE TABLE IDN_BASE_TABLE (
    PRODUCT_NAME VARCHAR2(20),
    PRIMARY KEY (PRODUCT_NAME)
);

-- Sequence for USERS table
CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1;

-- Core table with various column types
CREATE TABLE USERS (
    ID NUMBER(10) NOT NULL,
    USERNAME VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(255),
    STATUS VARCHAR2(25) DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    TENANT_ID NUMBER(10) DEFAULT 0,
    CONSTRAINT PK_USERS PRIMARY KEY (ID),
    CONSTRAINT UK_USERS_USERNAME UNIQUE (USERNAME),
    CONSTRAINT UK_USERS_EMAIL UNIQUE (EMAIL)
);

-- Sequence for USER_ROLES table
CREATE SEQUENCE USER_ROLES_SEQ START WITH 1 INCREMENT BY 1;

-- Table with foreign key reference
CREATE TABLE USER_ROLES (
    ID NUMBER(10) NOT NULL,
    USER_ID NUMBER(10) NOT NULL,
    ROLE_NAME VARCHAR2(100) NOT NULL,
    ASSIGNED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_USER_ROLES PRIMARY KEY (ID),
    CONSTRAINT FK_USER_ROLES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- Table with composite primary key
CREATE TABLE USER_ATTRIBUTES (
    USER_ID NUMBER(10) NOT NULL,
    ATTR_KEY VARCHAR2(100) NOT NULL,
    ATTR_VALUE VARCHAR2(1024),
    CONSTRAINT PK_USER_ATTRIBUTES PRIMARY KEY (USER_ID, ATTR_KEY),
    CONSTRAINT FK_USER_ATTR_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- Sequence for AUDIT_LOG table
CREATE SEQUENCE AUDIT_LOG_SEQ START WITH 1 INCREMENT BY 1;

-- Table for index testing
CREATE TABLE AUDIT_LOG (
    ID NUMBER(10) NOT NULL,
    USER_ID NUMBER(10),
    ACTION VARCHAR2(100) NOT NULL,
    RESOURCE_TYPE VARCHAR2(50),
    RESOURCE_ID VARCHAR2(255),
    TIMESTAMP TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DETAILS CLOB,
    CONSTRAINT PK_AUDIT_LOG PRIMARY KEY (ID)
);

CREATE INDEX IDX_AUDIT_USER ON AUDIT_LOG (USER_ID);
CREATE INDEX IDX_AUDIT_ACTION ON AUDIT_LOG (ACTION);
CREATE INDEX IDX_AUDIT_RESOURCE ON AUDIT_LOG (RESOURCE_TYPE, RESOURCE_ID);
CREATE INDEX IDX_AUDIT_TIMESTAMP ON AUDIT_LOG (TIMESTAMP);

-- Table with check constraint
CREATE TABLE TOKENS (
    TOKEN_ID VARCHAR2(255) NOT NULL,
    TOKEN_TYPE VARCHAR2(50) NOT NULL,
    USER_ID NUMBER(10) NOT NULL,
    EXPIRES_AT NUMBER(19) NOT NULL,
    STATE VARCHAR2(25) DEFAULT 'ACTIVE',
    CONSTRAINT PK_TOKENS PRIMARY KEY (TOKEN_ID),
    CONSTRAINT FK_TOKENS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT CHK_TOKEN_STATE CHECK (STATE IN ('ACTIVE', 'REVOKED', 'EXPIRED'))
);

