-- Delta: Remove tables from target (PostgreSQL)
-- Tests detection of missing tables
DROP TABLE IF EXISTS TOKENS CASCADE;
DROP TABLE IF EXISTS USER_ATTRIBUTES CASCADE;
DROP TABLE IF EXISTS USER_ROLES CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;

