-- Minimal Reference Schema for PostgreSQL Fast E2E Tests
-- Simplified schema covering all comparison dimensions

-- Base table (standalone, no dependencies)
CREATE TABLE IF NOT EXISTS IDN_BASE_TABLE (
    PRODUCT_NAME VARCHAR(20),
    PRIMARY KEY (PRODUCT_NAME)
);

-- Core table with various column types and sequences
CREATE SEQUENCE IF NOT EXISTS USERS_ID_SEQ;
CREATE TABLE IF NOT EXISTS USERS (
    ID INTEGER NOT NULL DEFAULT NEXTVAL('USERS_ID_SEQ'),
    USERNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255),
    STATUS VARCHAR(25) DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TENANT_ID INTEGER DEFAULT 0,
    CONSTRAINT UK_USERS_USERNAME UNIQUE (USERNAME),
    CONSTRAINT UK_USERS_EMAIL UNIQUE (EMAIL),
    PRIMARY KEY (ID)
);

-- Table with foreign key reference
CREATE SEQUENCE IF NOT EXISTS USER_ROLES_ID_SEQ;
CREATE TABLE IF NOT EXISTS USER_ROLES (
    ID INTEGER NOT NULL DEFAULT NEXTVAL('USER_ROLES_ID_SEQ'),
    USER_ID INTEGER NOT NULL,
    ROLE_NAME VARCHAR(100) NOT NULL,
    ASSIGNED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    CONSTRAINT FK_USER_ROLES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- Table with composite primary key
CREATE TABLE IF NOT EXISTS USER_ATTRIBUTES (
    USER_ID INTEGER NOT NULL,
    ATTR_KEY VARCHAR(100) NOT NULL,
    ATTR_VALUE VARCHAR(1024),
    PRIMARY KEY (USER_ID, ATTR_KEY),
    CONSTRAINT FK_USER_ATTR_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- Table for index testing
CREATE SEQUENCE IF NOT EXISTS AUDIT_LOG_ID_SEQ;
CREATE TABLE IF NOT EXISTS AUDIT_LOG (
    ID INTEGER NOT NULL DEFAULT NEXTVAL('AUDIT_LOG_ID_SEQ'),
    USER_ID INTEGER,
    ACTION VARCHAR(100) NOT NULL,
    RESOURCE_TYPE VARCHAR(50),
    RESOURCE_ID VARCHAR(255),
    TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DETAILS TEXT,
    PRIMARY KEY (ID)
);

CREATE INDEX IDX_AUDIT_USER ON AUDIT_LOG (USER_ID);
CREATE INDEX IDX_AUDIT_ACTION ON AUDIT_LOG (ACTION);
CREATE INDEX IDX_AUDIT_RESOURCE ON AUDIT_LOG (RESOURCE_TYPE, RESOURCE_ID);
CREATE INDEX IDX_AUDIT_TIMESTAMP ON AUDIT_LOG (TIMESTAMP);

-- Table with check constraint
CREATE TABLE IF NOT EXISTS TOKENS (
    TOKEN_ID VARCHAR(255) NOT NULL,
    TOKEN_TYPE VARCHAR(50) NOT NULL,
    USER_ID INTEGER NOT NULL,
    EXPIRES_AT BIGINT NOT NULL,
    STATE VARCHAR(25) DEFAULT 'ACTIVE',
    PRIMARY KEY (TOKEN_ID),
    CONSTRAINT FK_TOKENS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT CHK_TOKEN_STATE CHECK (STATE IN ('ACTIVE', 'REVOKED', 'EXPIRED'))
);

