-- Delta: Add extra tables to target (PostgreSQL)
-- Tests detection of extra tables
CREATE TABLE IF NOT EXISTS UNAUTHORIZED_TABLE (
    ID SERIAL PRIMARY KEY,
    DATA TEXT
);

CREATE TABLE IF NOT EXISTS DEBUG_LOG (
    ID SERIAL PRIMARY KEY,
    MESSAGE TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

