-- Delta: Add extra tables to target (MSSQL)
-- Tests detection of extra tables
CREATE TABLE UNAUTHORIZED_TABLE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    DATA NVARCHAR(MAX)
);

CREATE TABLE DEBUG_LOG (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    MESSAGE NVARCHAR(MAX),
    CREATED_AT DATETIME2 DEFAULT GETDATE()
);

