-- Delta: Remove tables from target (Oracle)
-- Tests detection of missing tables
DROP TABLE TOKENS CASCADE CONSTRAINTS;
DROP TABLE USER_ATTRIBUTES CASCADE CONSTRAINTS;
DROP TABLE USER_ROLES CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;

