-- Delta: Add extra columns to USERS table
-- Tests detection of unauthorized column additions

ALTER TABLE USERS ADD COLUMN PHONE_NUMBER VARCHAR(50);
ALTER TABLE USERS ADD COLUMN LAST_LOGIN TIMESTAMP;
ALTER TABLE USERS ADD COLUMN IS_ADMIN BOOLEAN DEFAULT FALSE;

