-- Minimal Reference Schema for Fast E2E Tests
-- This is a simplified schema that covers all comparison dimensions
-- Used for atomic tests to keep CI fast

-- Base table (standalone, no dependencies)
CREATE TABLE IF NOT EXISTS IDN_BASE_TABLE (
    PRODUCT_NAME VARCHAR(20),
    PRIMARY KEY (PRODUCT_NAME)
) ENGINE=InnoDB;

-- Core table with various column types and auto-increment
CREATE TABLE IF NOT EXISTS USERS (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255),
    STATUS VARCHAR(25) DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TENANT_ID INTEGER DEFAULT 0,
    CONSTRAINT UK_USERS_USERNAME UNIQUE (USERNAME),
    CONSTRAINT UK_USERS_EMAIL UNIQUE (EMAIL),
    PRIMARY KEY (ID)
) ENGINE=InnoDB;

-- Table with foreign key reference
CREATE TABLE IF NOT EXISTS USER_ROLES (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    USER_ID INTEGER NOT NULL,
    ROLE_NAME VARCHAR(100) NOT NULL,
    ASSIGNED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    CONSTRAINT FK_USER_ROLES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Table with composite primary key
CREATE TABLE IF NOT EXISTS USER_ATTRIBUTES (
    USER_ID INTEGER NOT NULL,
    ATTR_KEY VARCHAR(100) NOT NULL,
    ATTR_VALUE VARCHAR(1024),
    PRIMARY KEY (USER_ID, ATTR_KEY),
    CONSTRAINT FK_USER_ATTR_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Table for index testing
CREATE TABLE IF NOT EXISTS AUDIT_LOG (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    USER_ID INTEGER,
    ACTION VARCHAR(100) NOT NULL,
    RESOURCE_TYPE VARCHAR(50),
    RESOURCE_ID VARCHAR(255),
    TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DETAILS TEXT,
    PRIMARY KEY (ID),
    INDEX IDX_AUDIT_USER (USER_ID),
    INDEX IDX_AUDIT_ACTION (ACTION),
    INDEX IDX_AUDIT_RESOURCE (RESOURCE_TYPE, RESOURCE_ID),
    INDEX IDX_AUDIT_TIMESTAMP (TIMESTAMP)
) ENGINE=InnoDB;

-- Table with check constraint (MySQL 8.0+)
CREATE TABLE IF NOT EXISTS TOKENS (
    TOKEN_ID VARCHAR(255) NOT NULL,
    TOKEN_TYPE VARCHAR(50) NOT NULL,
    USER_ID INTEGER NOT NULL,
    EXPIRES_AT BIGINT NOT NULL,
    STATE VARCHAR(25) DEFAULT 'ACTIVE',
    PRIMARY KEY (TOKEN_ID),
    CONSTRAINT FK_TOKENS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT CHK_TOKEN_STATE CHECK (STATE IN ('ACTIVE', 'REVOKED', 'EXPIRED'))
) ENGINE=InnoDB;

