-- Delta: Add an extra table that doesn't exist in reference
-- This simulates unauthorized schema additions

CREATE TABLE IF NOT EXISTS UNAUTHORIZED_TABLE (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS DEBUG_LOG (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    MESSAGE TEXT,
    LEVEL VARCHAR(20),
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
) ENGINE=InnoDB;

