-- Minimal Reference Schema for MSSQL Fast E2E Tests
-- Simplified schema covering all comparison dimensions

-- Base table (standalone, no dependencies)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'IDN_BASE_TABLE')
CREATE TABLE IDN_BASE_TABLE (
    PRODUCT_NAME VARCHAR(20),
    PRIMARY KEY (PRODUCT_NAME)
);

-- Core table with various column types and identity
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'USERS')
CREATE TABLE USERS (
    ID INT NOT NULL IDENTITY(1,1),
    USERNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255),
    STATUS VARCHAR(25) DEFAULT 'ACTIVE',
    CREATED_AT DATETIME2 NOT NULL DEFAULT GETDATE(),
    TENANT_ID INT DEFAULT 0,
    CONSTRAINT UK_USERS_USERNAME UNIQUE (USERNAME),
    CONSTRAINT UK_USERS_EMAIL UNIQUE (EMAIL),
    PRIMARY KEY (ID)
);

-- Table with foreign key reference
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'USER_ROLES')
CREATE TABLE USER_ROLES (
    ID INT NOT NULL IDENTITY(1,1),
    USER_ID INT NOT NULL,
    ROLE_NAME VARCHAR(100) NOT NULL,
    ASSIGNED_AT DATETIME2 DEFAULT GETDATE(),
    PRIMARY KEY (ID),
    CONSTRAINT FK_USER_ROLES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- Table with composite primary key
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'USER_ATTRIBUTES')
CREATE TABLE USER_ATTRIBUTES (
    USER_ID INT NOT NULL,
    ATTR_KEY VARCHAR(100) NOT NULL,
    ATTR_VALUE VARCHAR(1024),
    PRIMARY KEY (USER_ID, ATTR_KEY),
    CONSTRAINT FK_USER_ATTR_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- Table for index testing
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'AUDIT_LOG')
CREATE TABLE AUDIT_LOG (
    ID INT NOT NULL IDENTITY(1,1),
    USER_ID INT,
    ACTION VARCHAR(100) NOT NULL,
    RESOURCE_TYPE VARCHAR(50),
    RESOURCE_ID VARCHAR(255),
    TIMESTAMP DATETIME2 NOT NULL DEFAULT GETDATE(),
    DETAILS NVARCHAR(MAX),
    PRIMARY KEY (ID)
);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IDX_AUDIT_USER')
CREATE INDEX IDX_AUDIT_USER ON AUDIT_LOG (USER_ID);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IDX_AUDIT_ACTION')
CREATE INDEX IDX_AUDIT_ACTION ON AUDIT_LOG (ACTION);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IDX_AUDIT_RESOURCE')
CREATE INDEX IDX_AUDIT_RESOURCE ON AUDIT_LOG (RESOURCE_TYPE, RESOURCE_ID);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IDX_AUDIT_TIMESTAMP')
CREATE INDEX IDX_AUDIT_TIMESTAMP ON AUDIT_LOG (TIMESTAMP);

-- Table with check constraint
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TOKENS')
CREATE TABLE TOKENS (
    TOKEN_ID VARCHAR(255) NOT NULL,
    TOKEN_TYPE VARCHAR(50) NOT NULL,
    USER_ID INT NOT NULL,
    EXPIRES_AT BIGINT NOT NULL,
    STATE VARCHAR(25) DEFAULT 'ACTIVE',
    PRIMARY KEY (TOKEN_ID),
    CONSTRAINT FK_TOKENS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT CHK_TOKEN_STATE CHECK (STATE IN ('ACTIVE', 'REVOKED', 'EXPIRED'))
);

