-- Delta: Drop constraints from tables (PostgreSQL)
-- Tests detection of missing constraints

ALTER TABLE USERS DROP CONSTRAINT IF EXISTS UK_USERS_EMAIL;
ALTER TABLE USER_ROLES DROP CONSTRAINT IF EXISTS FK_USER_ROLES_USER;
ALTER TABLE TOKENS DROP CONSTRAINT IF EXISTS CHK_TOKEN_STATE;

